# Site settings
title: Towering Pillar of Hats Security
email: hello@toweringpillarofhats.com
url: https://tpohs.github.io
description: "We hack your company to show you how crap your sysadmins are."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Towering Pillar of Hats Security

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Kurobeats

# Build settings
markdown: kramdown
permalink: pretty
